### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by jacquesCedric** [tabasku/harbour-neliapila#10]
I've made a few changes and am wondering if I should fork this project or open a pull request?

Cheers, and thanks for making this software in the first place!

**Comment by tabasku** [comment]
Hi @jacquesCedric . I can review pull requests but you are welcome to fork and release your own version as well. 
As you might see from commit history and open issues I dont really maintain project actively enough. I do have Sailfish device and use it sometimes but rarely get into developing. Be warned though, codebase is bit messy as it is my first SFOS project :)

**Comment by jacquesCedric** [comment]
Cool! Some of the changes are minor tweaks or bug fixes but there's a few more opinionated ones so if you don't like them I'll just release a fork.
It's always enjoyable to trawl messy code. It's my first time working with SFOS too, so there is zero judgment!
