### ISSUE TITLE
[feature request] Add option to browse catalog (non-paged thread listing)

### ISSUE THREAD

**Issue by szopin** [tabasku/harbour-neliapila#12]
On active boards you tend to see same threads over and over as you browse as by the time you get to second page threads from first have already slid to second. Adding an option for catalog view would be best. Quick and dirty hack is just changing in threads.py:
    threads = board.get_threads(page_no)
to:
threads = board.get_all_threads(board_id)
It takes forever, but works (have an old version of neliapila with this hack just for some boards, all functionality seems to remain working, but proper implementation would most likely require settings page and removing the navigation options)

**Comment by szopin** [comment]
It needs to be:
threads = board.get_all_threads(False)
It was taking ages because it was pulling all posts from whole board (oops)

**Comment by jacquesCedric** [comment]
I've written something that does this and also replaces the footer in post and thread pages with a pushUp menu. However I'll have to check over my changes and see if I've implemented it in the slow way, as you describe.

**Comment by szopin** [comment]
The slow way is the get_all_threads with extended=True from board.py, and takes over a minute, so most definitely not it, aside from lacking scroll bars it was working fine. Also tested the nested replies fix and it works great (even almost fixes replying to nested comments, weird as it seems to only work half of the time on the first nested layer)

**Comment by jacquesCedric** [comment]
I took the quick scroll elements out as they were annoying me but I'll add them again to keep continuity for existing users. I have no idea what the nested reply issue is and haven't yet experienced it but I'm still familiarizing myself with the codebase and QML generally. I'll amend the pull request and merge.

**Comment by szopin** [comment]
Replying in a nested comment is broken, sometimes works when you are only 1 comment into the chain, but if you go further it seems to try to reply to each and every one, probably flooding the api, opened #19 to track it, was pretty sure we already had this as an issue opened
