### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by jacquesCedric** [tabasku/harbour-neliapila#20]
Implement settings page with:
- Page or Catalog view
- QuickScroll toggle
- Boards to display
- Autorefresh timer?
- Implementing what's in the existing settings page

**Comment by szopin** [comment]
Boards to display seems to be working fine in current implementation? At least it's one swipe away from changing the board, if someone browses only one, then putting it behind settings page maybe would work. Rest seem fine. Maybe also auto-scroll to the last seen comment option? For the longer threads it's usually the last 3-5% of the thread that have new posts, even with scroll bar there is some scrolling back to continue reading if you revisit a thread after a while, at least maybe for pinned threads as they already are storing info, no idea if possible though. Autorefresh would be pretty awesome

**Comment by jacquesCedric** [comment]
Agree with all points! Yeah, had a bit of a lapse there with the boards and guess I want it to display favourites by default but that should be a separate issue.

**Comment by jacquesCedric** [comment]
Auto-refresh implemented a few commits ago and setting page implemented after merging of #36
