### ISSUE TITLE
Thread duplication

### ISSUE THREAD

**Issue by szopin** [tabasku/harbour-neliapila#21]
Sometimes threads get duplicated, I believe it's when you are refreshing at the same time update tick happens on the board, so last 1-2 threads from previous page get included on the next. Didn't see that behaviour in my hacky version, believe it's because the get_all_threads from board.py uses catalog, so should be immune to this, but not 100% sure as it's not easy to reproduce, happens once in a while (maybe proper timing and forcing 2g could help with reproducibility)

**Comment by jacquesCedric** [comment]
I was using a loop instead of a the actual API like you suggested (and were right to). Hopefully fixed now...

**Comment by szopin** [comment]
Seems fixed (or at least couldn't get it to show up again in the last 15 minutes of refreshing/scrolling), thanks!
