### ISSUE TITLE
Quickscroll missing from threadsview

### ISSUE THREAD

**Issue by szopin** [tabasku/harbour-neliapila#37]
The setting works great for postsview, but not there for threadsview, also (probably should be separate issue) going 'back to board' from pinned view is now returning to bottom which without scrollbar is a pita

**Comment by szopin** [comment]
Correction: quickscroll in threadsview works, but requires restart of app for the change to take effect

**Comment by jacquesCedric** [comment]
I couldn't think of a nice way to have the settings take place immediately and refresh the app after change. That would be smarter though as then a restart after restoring default settings could be avoided too.

I'll push something to fix the pinned -> threads issues now.

**Comment by szopin** [comment]
Fixed long time ago
