### ISSUE TITLE
Posting from neliapila results in ban

### ISSUE THREAD

**Issue by szopin** [tabasku/harbour-neliapila#47]
3 months, with reason Proxy/VPN

**Comment by szopin** [comment]
Since like 3 days was getting banned after first post that seems to work fine, on second post you get the banned msg. Thought it was maybe mods range ip banning my mobile network, but today tried first to post from browser, went through without problem, post from neliapila again resulted in 3 month ban, something in how neliapila handles posting must be triggering it

**Comment by szopin** [comment]
Seems to be fixed, just posted a test post and it went through, must've been some buggy setting on 4chan side

**Comment by szopin** [comment]
Aaaand it's back again, no freaking idea if it is only neliapila issue or that + isp, but again 3 months given for a normal post from nelia, ffs

**Comment by szopin** [comment]
Ok just tested with android app (omnichan) and on fresh IP, it went through, then post from nelia resulted in a ban so it is not simple IP ban, nelia is involved even though worked fine yesterday for multiple postings, some combination of ip/clientid is triggering it again and no idea how to troubleshoot, but leaving open for now

**Comment by szopin** [comment]
In any case left some feedback as suggested on 4chan irc, no idea if it'll help, but considering the unknowns of their ban system not sure we can do more

**Comment by szopin** [comment]
Wireshark from openrepos kinda works on the phone, but sadly all the posting traffic is behind tls (neliapila does seem to use http for GETs though as seen that), sadly global proxy settings are broken so could not route the traffic to mitmproxy to compare nelia requests vs omnichan to figure out the difference that trips 4chan into banning, if someone has a suggestion how to either set it to work with mobile connection or otherwise be able to extract the requests for compare (console.logging?) I'm all ears

**Comment by tabasku** [comment]
One thing which might look weird to 4chan side is Agent header which we could try to change. I used old Firefox agent header because I found it worked on another CLI client made with Python.
https://github.com/tabasku/harbour-neliapila/blob/master/py/posting.py#L24

I was trying to review how Clover handles posting and I'm bit confused what is uniqueIP's purpose in posting: https://github.com/chandevel/Clover/blob/0c58c619ade21b32aa9df209fc88a5cf3eb16c80/Clover/app/src/main/java/org/floens/chan/core/model/Post.java#L213

**Comment by szopin** [comment]
I remember trying to tweak the user_agent at one point (not to any particular different one, just changing one digit) and it had no impact, but not sure if in posting.py, might've been captcha.py, so maybe that's why.
I think the uniqueIPs is just there to update the number of unique posters after posting (if it was your first post to a thread it would get +1 (or +however many new people posted in that time interval)), don't think we track/show this in nelia

**Comment by szopin** [comment]
Closing this as for the time being not relevant, no way to test anyway if it keeps happening, also no confirmations from other users, which would suggest it was tied to some spam-activity from my ISP? (maybe this is the reason they upped the captcha level to high, breaking posting even? Unlikely but who knows)
