### ISSUE TITLE
Captcha no longer loads on 2.1.0.x

### ISSUE THREAD

**Issue by szopin** [tabasku/harbour-neliapila#50]
Not much more to say, jolla C, 2.1.0.19 and 2.1.0.20 both have an endless loading circle when trying to post

**Comment by tabasku** [comment]
I believe I had this issue with Clover as well. It seems 4chan might have disabled no-javascript Captcha on their site which Neliapila was also using. This would require some time to reimplement captcha with js one..
https://github.com/chandevel/Clover/issues/757

**Comment by tabasku** [comment]
Also 4chanX seems to be affected by this. Not sure if this is intentional from admins or not
https://github.com/ccd0/4chan-x/issues/2500

**Comment by szopin** [comment]
And now it works again, so closing as currently fixed
