### ISSUE TITLE
Threads with “”„ (and single one that is not on jolla keyboard) get substituted for \x**\x**\x** after pinning

### ISSUE THREAD

**Issue by szopin** [tabasku/harbour-neliapila#9]
Probably related to previous issue and some kind of unicode substitution is happening when storing the contents in mysql, this one is just cosmetic though as thread can still be pinned and works fine after opening, just pinned view displays this

**Comment by szopin** [comment]
Example:
http://oi65.tinypic.com/2zfomrs.jpg

**Comment by jacquesCedric** [comment]
I've just drafted [this](https://github.com/tabasku/harbour-neliapila/compare/pinned-post-fixes)

From my understanding it'd be a more future-proof solution where we won't have to individually account for HTML entities, but I'm not super familiar with python!
